from __future__ import annotations

from typing import Any, Optional, Protocol


class SeasonView(Protocol):
    """Interface describing the UI surface SeasonManager interacts with."""

    def show_banner(self) -> None: ...

    def show_week_header(self, *, year: int, week: int, week_max: int, month: int) -> None: ...

    def display_story_event(self, message: str) -> None: ...

    def display_info(self, message: str) -> None: ...

    def display_warning(self, message: str) -> None: ...

    def display_error(self, message: str) -> None: ...

    def display_rivalry_detected(self, school_name: str) -> None: ...

    def display_rivalry_aura(self) -> None: ...

    def prompt_continue(self, prompt: str = "Press Enter to continue...") -> None: ...

    def prompt_yes_no(self, prompt: str) -> bool: ...

    def prompt_weekly_menu(self, *, scouting_available: bool, context: Any, session: Any, state: Any) -> str: ...

    def prompt_command_menu(self, *, context: Any, session: Any, state: Any) -> str: ...

    def prompt_smart_sim(self, *, current_week: int, context: Any, session: Any, state: Any) -> Optional[int]: ...

    def show_character_sheet(self, session: Any, snapshot: dict) -> None: ...

    def show_save_menu(self) -> None: ...

    def show_scouting_menu(self, context: Any) -> None: ...

    def show_weekly_dashboard(self, summary: Any) -> None: ...

    def show_smart_sim_stop(self, reason: str) -> None: ...

    def show_progress(self, message: str, end: str = "\n") -> None: ...

    def show_fatal_error(self, title: str, body: str, details: Optional[str] = None) -> None: ...

    # Main menu / lifecycle helpers
    def prompt_main_menu(self, *, player_info: str, has_save: bool) -> str: ...

    def prompt_rebuild_world(self) -> bool: ...

    def prompt_new_career(self) -> bool: ...

    def announce_world_gen(self) -> None: ...

    def announce_world_gen_complete(self) -> None: ...

    def announce_new_career_ready(self) -> None: ...

    def announce_player_created(self) -> None: ...

    def announce_character_creation(self) -> None: ...
