"""Centralized trait metadata for King of the Diamond RPG."""
from __future__ import annotations

from typing import Dict


def _trait(name: str, description: str, **kwargs) -> Dict[str, object]:
    payload = {"name": name, "description": description}
    payload.update(kwargs)
    return payload


BATTER_TRAITS: Dict[str, Dict[str, object]] = {
    "cheetah": _trait(
        "Cheetah",
        "Explosive acceleration that weaponizes every walk or single.",
        category="batting",
        type="passive_buff",
        requirements=[
            {"stat": "speed", "min": 65},
            {"stat": "discipline", "min": 48},
        ],
        modifiers={"speed": 6, "discipline": 2},
        ai_tendency={"steal_aggression": 1.35},
        synergy_tags={"speed": 3, "aggression": 1},
        alignment="positive",
    ),
    "clutch_hitter": _trait(
        "Clutch Hitter",
        "Performance spikes with the tying run aboard late.",
        category="batting",
        type="situational",
        condition="late_inning_pressure",
        requirements=[
            {"stat": "contact", "min": 50},
            {"stat": "power", "min": 55},
            {"stat": "clutch", "min": 70},
        ],
        modifiers={"contact": 12, "power": 10},
        synergy_tags={"clutch": 3, "power": 1},
        alignment="positive",
    ),
    "power_hitter": _trait(
        "Power Hitter",
        "Uppercut swing built for the seats.",
        category="batting",
        type="passive_buff",
        requirements=[
            {"stat": "power", "min": 60},
            {"stat": "contact", "min": 40},
        ],
        modifiers={"power": 10, "contact": -4},
        synergy_tags={"power": 3, "discipline": -1},
        alignment="positive",
    ),
    "contact_specialist": _trait(
        "Contact Specialist",
        "Lives on the barrel; strikeouts are a rarity.",
        category="batting",
        type="passive_buff",
        requirements=[
            {"stat": "contact", "min": 52},
            {"stat": "discipline", "min": 60},
        ],
        modifiers={"contact": 9, "discipline": 4, "power": -3},
        synergy_tags={"discipline": 2, "bat_control": 3},
        alignment="positive",
    ),
    "gap_specialist": _trait(
        "Gap Specialist",
        "Sprays doubles with picture-perfect barrels.",
        category="batting",
        type="passive_buff",
        requirements=[
            {"stat": "contact", "min": 48},
            {"stat": "power", "min": 45, "max": 72},
        ],
        modifiers={"contact": 6, "power": 3},
        synergy_tags={"bat_control": 2, "power": 1},
        alignment="positive",
    ),
    "platoon_hitter": _trait(
        "Platoon Hitter",
        "Thrives when enjoying the handedness edge.",
        category="batting",
        type="situational",
        condition="platoon_advantage",
        requirements=[{"stat": "contact", "min": 50}],
        modifiers={"contact": 8, "power": 5},
        synergy_tags={"matchup": 3},
        alignment="positive",
    ),
    "leadoff_catalyst": _trait(
        "Leadoff Catalyst",
        "Ignites games from pitch one.",
        category="batting",
        type="situational",
        condition="lineup_leadoff",
        requirements=[{"stat": "speed", "min": 58}, {"stat": "contact", "min": 50}],
        modifiers={"speed": 8, "contact": 5},
        synergy_tags={"speed": 2, "support": 2},
        alignment="role",
    ),
    "pull_hitter": _trait(
        "Pull Hitter",
        "Crushes anything inside but sacrifices spray chart balance.",
        category="batting",
        type="passive_buff",
        requirements=[{"stat": "power", "min": 55}],
        modifiers={"power": 7, "contact": -4},
        ai_tendency={"pull_bias": 1.35},
        synergy_tags={"power": 2, "aggression": 1},
        alignment="neutral",
    ),
    "opposite_field_master": _trait(
        "Opposite Field Master",
        "Comfortably pokes lasers the other way.",
        category="batting",
        type="passive_buff",
        requirements=[{"stat": "contact", "min": 50}, {"stat": "discipline", "min": 55}],
        modifiers={"contact": 7, "discipline": 3},
        ai_tendency={"spray_opposite": 1.25},
        synergy_tags={"bat_control": 2, "discipline": 1},
        alignment="positive",
    ),
    "free_swinger": _trait(
        "Free Swinger",
        "Hacks early, hunts damage, lives with the whiffs.",
        category="batting",
        type="behavior",
        requirements=[{"stat": "discipline", "max": 55}],
        ai_tendency={"swing_aggression": 1.4},
        modifiers={"power": 3, "discipline": -6},
        synergy_tags={"aggression": 3},
        alignment="neutral",
    ),
    "tough_out": _trait(
        "Tough Out",
        "Spoils nastiest pitches with two strikes.",
        category="batting",
        type="situational",
        condition="two_strike_battle",
        requirements=[{"stat": "discipline", "min": 58}],
        modifiers={"contact": 6, "discipline": 4},
        synergy_tags={"resilience": 2, "discipline": 1},
        alignment="positive",
    ),
    "fast_hands": _trait(
        "Fast Hands",
        "Lightning bat speed erases elite fastballs.",
        category="batting",
        type="passive_buff",
        requirements=[{"stat": "contact", "min": 55}, {"stat": "power", "min": 50}],
        modifiers={"contact": 6, "power": 4},
        synergy_tags={"bat_speed": 3, "power": 1},
        alignment="positive",
    ),
    "hot_streak": _trait(
        "Hot Streak",
        "Feeds off current heater to turbocharge offense.",
        category="batting",
        type="situational",
        condition="hot_streak_active",
        requirements=[],
        modifiers={"contact": 5, "power": 5, "discipline": 2},
        synergy_tags={"momentum": 4},
        alignment="positive",
    ),
    "walk_machine": _trait(
        "Walk Machine",
        "Elite zone control manufactures OBP.",
        category="batting",
        type="passive_buff",
        requirements=[{"stat": "discipline", "min": 68}, {"stat": "contact", "min": 45}],
        modifiers={"discipline": 8, "contact": 3},
        ai_tendency={"take_rate": 1.3},
        synergy_tags={"discipline": 4},
        alignment="positive",
    ),
    "foul_ball_expert": _trait(
        "Foul Ball Expert",
        "Turns every two-strike battle into a war of attrition.",
        category="batting",
        type="situational",
        condition="two_strike_battle",
        requirements=[{"stat": "discipline", "min": 55}],
        modifiers={"contact": 4},
        ai_tendency={"extend_at_bat": 1.4},
        synergy_tags={"resilience": 2},
        alignment="positive",
    ),
    "pinch_hitter": _trait(
        "Pinch-Hitter",
        "Cold off the bench but nails the biggest knock.",
        category="batting",
        type="situational",
        condition="pinch_hitting_moment",
        requirements=[{"stat": "contact", "min": 48}, {"stat": "clutch", "min": 65}],
        modifiers={"contact": 8, "power": 6},
        synergy_tags={"clutch": 2},
        alignment="role",
    ),
    "bunt_master": _trait(
        "Bunt Master",
        "Drops precision bunts for hits or sacrifices.",
        category="batting",
        type="behavior",
        requirements=[
            {"stat": "contact", "min": 45},
            {"stat": "discipline", "min": 55},
            {"stat": "speed", "min": 48},
        ],
        modifiers={"contact": 3},
        ai_tendency={"bunt_frequency": 1.6},
        synergy_tags={"bat_control": 2, "speed": 1},
        alignment="positive",
    ),
}


FIELDING_TRAITS: Dict[str, Dict[str, object]] = {
    "gold_glove": _trait(
        "Gold Glove",
        "Vacuum cleaner defense with flair and consistency.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 70}],
        modifiers={"fielding": 10, "throwing": 3},
        synergy_tags={"defense": 4},
        alignment="positive",
    ),
    "defensive_anchor": _trait(
        "Defensive Anchor",
        "Locks down the hot corner with consistency.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 58}, {"stat": "throwing", "min": 65}],
        modifiers={"fielding": 8, "throwing": 3},
        synergy_tags={"defense": 3},
        alignment="positive",
    ),
    "laser_arm": _trait(
        "Laser Arm",
        "Hoses runners with elite carry and accuracy.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "throwing", "min": 70}],
        modifiers={"throwing": 10, "fielding": 2},
        synergy_tags={"arm_strength": 4},
        alignment="positive",
    ),
    "field_general": _trait(
        "Field General",
        "Catcher provides steady leadership and pitch calling.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "position", "equals": "Catcher"}, {"stat": "catcher_leadership", "min": 60}],
        modifiers={"fielding": 5, "discipline": 3},
        synergy_tags={"leadership": 2},
        alignment="support",
    ),
    "spider_man": _trait(
        "Spider Man",
        "Absurd range, steals extra-base hits nightly.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "speed", "min": 62}, {"stat": "fielding", "min": 60}],
        modifiers={"fielding": 8, "speed": 4},
        synergy_tags={"range": 4},
        alignment="positive",
    ),
    "sniper_arm": _trait(
        "Sniper Arm",
        "Outfield cannon keeps runners glued.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "throwing", "min": 75}, {"stat": "fielding", "min": 55}],
        modifiers={"throwing": 9},
        synergy_tags={"arm_strength": 4},
        alignment="positive",
    ),
    "pickoff_specialist": _trait(
        "Pickoff Specialist",
        "Lightning moves neutralize running games.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "position", "equals": "Pitcher"}, {"stat": "control", "min": 55}],
        modifiers={"control": 4, "fielding": 3},
        synergy_tags={"awareness": 2},
        alignment="positive",
    ),
    "quick_reflexes": _trait(
        "Quick Reflexes",
        "Snags rockets before they clear the infield.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 55}],
        modifiers={"fielding": 6, "throwing": 2},
        synergy_tags={"reaction": 3},
        alignment="positive",
    ),
    "sure_hands": _trait(
        "Sure Hands",
        "Glove stays steady no matter the stakes.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 58}],
        modifiers={"fielding": 7},
        synergy_tags={"defense": 3},
        alignment="positive",
    ),
    "double_play_specialist": _trait(
        "Double Play Specialist",
        "Receives, transfers, and pivots at warp speed.",
        category="fielding",
        type="situational",
        condition="double_play_situation",
        requirements=[{"stat": "fielding", "min": 55}, {"stat": "speed", "min": 50}],
        modifiers={"fielding": 6, "throwing": 4},
        synergy_tags={"range": 2},
        alignment="positive",
    ),
    "jumping_jack": _trait(
        "Jumping Jack",
        "Skies at the wall to rob homers.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "speed", "min": 58}],
        modifiers={"fielding": 5, "speed": 3},
        synergy_tags={"range": 2},
        alignment="positive",
    ),
    "glove_wizard": _trait(
        "Glove Wizard",
        "Turns highlight plays routine, everywhere on the diamond.",
        category="fielding",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 60}],
        modifiers={"fielding": 8},
        synergy_tags={"defense": 4},
        alignment="positive",
    ),
    "clutch_defender": _trait(
        "Clutch Defender",
        "Late-inning nerves only sharpen his glove.",
        category="fielding",
        type="situational",
        condition="clutch_defense",
        requirements=[{"stat": "fielding", "min": 58}],
        modifiers={"fielding": 9},
        synergy_tags={"clutch": 2, "defense": 2},
        alignment="positive",
    ),
}


PITCHING_TRAITS: Dict[str, Dict[str, object]] = {
    "control_freak": _trait(
        "Control Freak",
        "Pinpoint command regardless of count.",
        category="pitching",
        type="passive_buff",
        requirements=[
            {"stat": "position", "equals": "Pitcher"},
            {"stat": "control", "min": 55},
            {"stat": "volatility", "max": 40},
        ],
        modifiers={"control": 7, "command": 4},
        synergy_tags={"discipline": 2},
        alignment="positive",
    ),
    "iron_will": _trait(
        "Iron Will",
        "Never-say-die mentality on the bump.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "mental", "min": 65}, {"stat": "drive", "min": 65}, {"stat": "morale", "min": 60}],
        modifiers={"mental": 5, "clutch": 4},
        synergy_tags={"resilience": 3},
        alignment="positive",
    ),
    "strikeout_king": _trait(
        "Strikeout King",
        "Overpowers lineups with whiffs.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "velocity", "min": 130}, {"stat": "movement", "min": 55}],
        modifiers={"velocity": 5, "movement": 4},
        synergy_tags={"power": 3, "putaway": 2},
        alignment="positive",
    ),
    "ground_ball_machine": _trait(
        "Ground Ball Machine",
        "Sinkerballer who gobbles double plays.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "movement", "min": 58}, {"stat": "command", "min": 52}],
        modifiers={"movement": 6, "command": 3},
        synergy_tags={"weak_contact": 3},
        alignment="positive",
    ),
    "control_artist": _trait(
        "Control Artist",
        "Paints edges with zero fear.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "control", "min": 60}, {"stat": "command", "min": 55}],
        modifiers={"control": 8, "command": 5},
        synergy_tags={"discipline": 2},
        alignment="positive",
    ),
    "big_game_pitcher": _trait(
        "Big Game Pitcher",
        "More dangerous the brighter the lights.",
        category="pitching",
        type="situational",
        condition="big_game_stage",
        requirements=[{"stat": "clutch", "min": 68}],
        modifiers={"control": 5, "movement": 4},
        synergy_tags={"clutch": 3},
        alignment="positive",
    ),
    "workhorse": _trait(
        "Workhorse",
        "Body built for 120-pitch marathons.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "position", "equals": "Pitcher"}, {"stat": "stamina", "min": 60}],
        modifiers={"stamina": 5},
        roll_modifiers={"fatigue": -0.2, "injury": -0.08},
        synergy_tags={"durability": 4},
        alignment="positive",
    ),
    "ace_stuff": _trait(
        "Ace Stuff",
        "Everything explodes on the radar gun and Rapsodo.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "velocity", "min": 132}, {"stat": "movement", "min": 58}],
        modifiers={"velocity": 4, "movement": 4},
        synergy_tags={"power": 3},
        alignment="positive",
    ),
    "flame_thrower": _trait(
        "Flame Thrower",
        "Triple-digit heater overwhelms hitters.",
        category="pitching",
        type="passive_buff",
        requirements=[
            {"stat": "position", "equals": "Pitcher"},
            {"stat": "velocity", "min": 132},
            {"stat": "control", "min": 55},
        ],
        modifiers={"velocity": 6, "movement": 2},
        synergy_tags={"power": 3},
        alignment="positive",
    ),
    "unpredictable": _trait(
        "Unpredictable",
        "Hitters never know if it's a dot or a wild ride.",
        category="pitching",
        type="behavior",
        requirements=[{"stat": "volatility", "min": 55}],
        modifiers={"movement": 3, "control": -4},
        ai_tendency={"mix_rate": 1.25},
        synergy_tags={"chaos": 3},
        alignment="neutral",
    ),
    "late_breaker": _trait(
        "Late Breaker",
        "Pitches fall off a cliff at the plate.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "movement", "min": 62}],
        modifiers={"movement": 6},
        synergy_tags={"putaway": 2},
        alignment="positive",
    ),
    "pitching_ninja": _trait(
        "Pitching Ninja",
        "Mastery of off-speed sequencing.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "command", "min": 58}, {"stat": "movement", "min": 55}],
        modifiers={"command": 6, "movement": 3},
        synergy_tags={"deception": 3},
        alignment="positive",
    ),
    "situational_ace": _trait(
        "Situational Ace",
        "Thrives when the bullpen phone rings late.",
        category="pitching",
        type="situational",
        condition="bullpen_fireman",
        requirements=[{"stat": "command", "min": 58}, {"stat": "clutch", "min": 68}],
        modifiers={"control": 5, "movement": 3},
        synergy_tags={"clutch": 2},
        alignment="positive",
    ),
    "sinker_specialist": _trait(
        "Sinker Specialist",
        "Heavy sinker wrecks launch angles.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "movement", "min": 55}],
        modifiers={"movement": 5, "command": 2},
        synergy_tags={"weak_contact": 2},
        alignment="positive",
    ),
    "mental_wall": _trait(
        "Mental Wall",
        "Shrugs off bad luck, never melts down.",
        category="pitching",
        type="situational",
        condition="high_pressure_moment",
        requirements=[{"stat": "mental", "min": 72}, {"stat": "discipline", "min": 65}, {"stat": "volatility", "max": 35}],
        modifiers={"mental": 8, "discipline": 6, "clutch": 6},
        synergy_tags={"composure": 4},
        alignment="positive",
    ),
    "high_heat": _trait(
        "High Heat",
        "Lives up in the zone at 150 kph.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "velocity", "min": 135}],
        modifiers={"velocity": 4, "control": -3},
        synergy_tags={"power": 3},
        alignment="positive",
    ),
    "breaking_ball_master": _trait(
        "Breaking Ball Master",
        "Spikes RPMs and shapes at will.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "movement", "min": 60}],
        modifiers={"movement": 7},
        synergy_tags={"deception": 3},
        alignment="positive",
    ),
    "shutdown_closer": _trait(
        "Shutdown Closer",
        "Cold blood in the ninth inning.",
        category="pitching",
        type="situational",
        condition="closer_ninth",
        requirements=[
            {"stat": "position", "equals": "Pitcher"},
            {"stat": "role", "equals_any": ["CLOSER", "RELIEVER"]},
            {"stat": "clutch", "min": 70},
            {"stat": "volatility", "max": 45},
        ],
        modifiers={"control": 4, "movement": 3},
        synergy_tags={"clutch": 3},
        alignment="positive",
    ),
    "outfield_coverage": _trait(
        "Outfield Coverage",
        "Fields bunts and comebackers like an extra infielder.",
        category="pitching",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 50}],
        modifiers={"fielding": 4, "throwing": 2},
        synergy_tags={"defense": 2},
        alignment="support",
    ),
}


MENTAL_TRAITS: Dict[str, Dict[str, object]] = {
    "team_leader": _trait(
        "Team Leader",
        "Steadies dugout emotions and raises team belief.",
        category="mental",
        type="aura",
        requirements=[{"stat": "drive", "min": 65}, {"stat": "morale", "min": 65}],
        team_effects={"confidence": 3},
        synergy_tags={"leadership": 4},
        alignment="support",
    ),
    "mentor": _trait(
        "Mentor",
        "Accelerates growth for youngsters.",
        category="mental",
        type="aura",
        requirements=[{"stat": "discipline", "min": 60}, {"stat": "age", "min": 18}],
        team_effects={"development_boost": 0.05},
        synergy_tags={"leadership": 3},
        alignment="support",
    ),
    "ice_in_the_veins": _trait(
        "Ice in the Veins",
        "Pulse barely moves in chaos.",
        category="mental",
        type="situational",
        condition="high_pressure_moment",
        requirements=[{"stat": "mental", "min": 68}],
        modifiers={"mental": 7, "clutch": 6},
        synergy_tags={"composure": 4},
        alignment="positive",
    ),
    "resilient": _trait(
        "Resilient",
        "Bounces back immediately after bad breaks.",
        category="mental",
        type="passive_buff",
        requirements=[{"stat": "mental", "min": 60}],
        modifiers={"mental": 5},
        synergy_tags={"resilience": 4},
        alignment="positive",
    ),
    "fire_in_the_belly": _trait(
        "Fire in the Belly",
        "Responds to deficits with fury.",
        category="mental",
        type="situational",
        condition="team_trailing",
        requirements=[{"stat": "drive", "min": 60}],
        modifiers={"power": 4, "clutch": 4},
        synergy_tags={"aggression": 2, "clutch": 1},
        alignment="positive",
    ),
    "undercover_agent": _trait(
        "Undercover Agent",
        "Reads signs, narrows windows for pitchers.",
        category="mental",
        type="situational",
        condition="scouting_edge",
        requirements=[{"stat": "discipline", "min": 58}],
        modifiers={"discipline": 4},
        synergy_tags={"awareness": 3},
        alignment="support",
    ),
    "clutch_performer": _trait(
        "Clutch Performer",
        "Late innings, extra innings, RISP—they deliver.",
        category="mental",
        type="situational",
        condition="clutch_superstate",
        requirements=[{"stat": "clutch", "min": 70}],
        modifiers={"contact": 6, "power": 6},
        synergy_tags={"clutch": 4},
        alignment="positive",
    ),
    "cerebral_player": _trait(
        "Cerebral Player",
        "Game awareness flips hidden levers.",
        category="mental",
        type="passive_buff",
        requirements=[{"stat": "discipline", "min": 60}],
        modifiers={"discipline": 4, "mental": 4},
        synergy_tags={"awareness": 4},
        alignment="support",
    ),
    "heart_of_the_team": _trait(
        "Heart of the Team",
        "Vocal glue guy who bumps morale when storms hit.",
        category="mental",
        type="aura",
        requirements=[{"stat": "morale", "min": 70}],
        team_effects={"morale": 4},
        synergy_tags={"leadership": 3},
        alignment="support",
    ),
    "selfless": _trait(
        "Selfless",
        "Will bunt, move runners, and take HBPs for the greater good.",
        category="mental",
        type="behavior",
        requirements=[{"stat": "discipline", "min": 55}],
        ai_tendency={"teamplay_bias": 1.3},
        synergy_tags={"support": 3},
        alignment="positive",
    ),
    "spark_plug": _trait(
        "Spark Plug",
        "Relentless energy spikes morale and tempo.",
        category="mental",
        type="aura",
        requirements=[{"stat": "speed", "min": 55}, {"stat": "drive", "min": 60}],
        team_effects={"tempo": 0.05, "morale": 2},
        synergy_tags={"leadership": 2, "speed": 1},
        alignment="support",
    ),
}


SPECIALIZED_TRAITS: Dict[str, Dict[str, object]] = {
    "speed_demon": _trait(
        "Speed Demon",
        "Pure chaos on the bases and in the gaps.",
        category="special",
        type="passive_buff",
        requirements=[{"stat": "speed", "min": 60}],
        modifiers={"speed": 6},
        ai_tendency={"steal_aggression": 1.2},
        synergy_tags={"speed": 3},
        alignment="positive",
    ),
    "durable": _trait(
        "Durable",
        "Stays on the field through the grind.",
        category="special",
        type="passive_buff",
        requirements=[{"stat": "stamina", "min": 55}],
        roll_modifiers={"injury": -0.15},
        modifiers={"stamina": 4},
        synergy_tags={"durability": 4},
        alignment="positive",
    ),
    "shutdown": _trait(
        "Shutdown",
        "Crafts zeros in any high-stress frame.",
        category="special",
        type="situational",
        condition="shutdown_mode",
        requirements=[{"stat": "clutch", "min": 68}],
        modifiers={"mental": 6, "control": 4},
        synergy_tags={"clutch": 3},
        alignment="positive",
    ),
    "breaking_point": _trait(
        "Breaking Point",
        "Excels when pressure is low; tense games unravel them.",
        category="special",
        type="situational",
        condition="low_pressure_window",
        requirements=[],
        modifiers={"contact": 5, "control": 4},
        synergy_tags={"composure": -2},
        alignment="neutral",
    ),
    "mr_utility": _trait(
        "Mr. Utility",
        "Competent everywhere; coaches can shuffle daily.",
        category="special",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 55}],
        modifiers={"fielding": 4},
        synergy_tags={"utility": 4},
        alignment="support",
    ),
    "pain_tolerance": _trait(
        "Pain Tolerance",
        "Plays through knocks with small drop-offs.",
        category="special",
        type="passive_buff",
        requirements=[{"stat": "drive", "min": 58}],
        roll_modifiers={"injury": -0.05},
        modifiers={"mental": 3},
        synergy_tags={"durability": 2},
        alignment="positive",
    ),
    "fearless": _trait(
        "Fearless",
        "Silences hostile crowds and aces alike.",
        category="special",
        type="situational",
        condition="hostile_environment",
        requirements=[{"stat": "mental", "min": 62}],
        modifiers={"mental": 5, "clutch": 4},
        synergy_tags={"composure": 3},
        alignment="positive",
    ),
    "catchers_mind": _trait(
        "Catcher's Mind",
        "Sees pitch sequencing like a veteran backstop.",
        category="special",
        type="passive_buff",
        requirements=[{"stat": "catcher_leadership", "min": 55}],
        modifiers={"command": 3, "discipline": 3},
        synergy_tags={"awareness": 3},
        alignment="support",
    ),
    "superstitious": _trait(
        "Superstitious",
        "Routine locked; deviation tanks production.",
        category="special",
        type="situational",
        condition="routine_online",
        requirements=[],
        modifiers={"contact": 5, "power": 3},
        synergy_tags={"ritual": 3},
        alignment="neutral",
    ),
    "base_stealer": _trait(
        "Base Stealer",
        "Times pitchers perfectly for thefts.",
        category="special",
        type="behavior",
        requirements=[{"stat": "speed", "min": 58}, {"stat": "discipline", "min": 55}],
        ai_tendency={"steal_aggression": 1.5},
        modifiers={"speed": 4},
        synergy_tags={"speed": 2, "aggression": 1},
        alignment="positive",
    ),
    "power_surge": _trait(
        "Power Surge",
        "Momentum-based slugger who stacks dingers in bunches.",
        category="special",
        type="situational",
        condition="hot_streak_active",
        requirements=[{"stat": "power", "min": 60}],
        modifiers={"power": 8},
        synergy_tags={"power": 3, "momentum": 2},
        alignment="positive",
    ),
    "glass_cannon": _trait(
        "Glass Cannon",
        "Explosive output but fragile frame.",
        category="special",
        type="passive_debuff",
        requirements=[{"stat": "power", "min": 60}, {"stat": "stamina", "max": 48}],
        modifiers={"power": 6, "stamina": -6},
        roll_modifiers={"fatigue": 0.18, "injury": 0.22},
        synergy_tags={"power": 3, "durability": -4},
        alignment="negative",
    ),
    "injury_prone": _trait(
        "Injury Prone",
        "Body just won't cooperate over long seasons.",
        category="special",
        type="passive_debuff",
        requirements=[],
        roll_modifiers={"injury": 0.35},
        modifiers={"stamina": -5},
        synergy_tags={"durability": -4},
        alignment="negative",
        allow_progression=False,
    ),
}


BAD_TRAITS: Dict[str, Dict[str, object]] = {
    "inconsistent": _trait(
        "Inconsistent",
        "Roller-coaster results make coaches uneasy.",
        category="negative",
        type="passive_debuff",
        requirements=[],
        modifiers={"contact": -4, "control": -4},
        synergy_tags={"volatility": 3},
        alignment="negative",
    ),
    "choker": _trait(
        "Choker",
        "Presses too hard under bright lights.",
        category="negative",
        type="situational",
        condition="late_inning_pressure",
        requirements=[],
        modifiers={"contact": -12, "power": -10},
        synergy_tags={"clutch": -4},
        alignment="negative",
        allow_progression=False,
    ),
    "freezer": _trait(
        "Freezer",
        "Playoff nerves freeze mechanics.",
        category="negative",
        type="situational",
        condition="postseason_stage",
        requirements=[],
        modifiers={"contact": -6, "control": -6},
        synergy_tags={"clutch": -3},
        alignment="negative",
    ),
    "easy_out": _trait(
        "Easy Out",
        "Cannot track breaking balls at all.",
        category="negative",
        type="passive_debuff",
        requirements=[],
        modifiers={"contact": -8},
        synergy_tags={"bat_control": -3},
        alignment="negative",
    ),
    "base_running_hazard": _trait(
        "Base Running Hazard",
        "Overly reckless on the basepaths.",
        category="negative",
        type="behavior",
        requirements=[],
        ai_tendency={"steal_aggression": 1.2},
        modifiers={"discipline": -4},
        synergy_tags={"aggression": 2, "awareness": -2},
        alignment="negative",
    ),
    "defensive_liability": _trait(
        "Defensive Liability",
        "Stone hands and cement feet.",
        category="negative",
        type="passive_debuff",
        requirements=[],
        modifiers={"fielding": -9},
        synergy_tags={"defense": -4},
        alignment="negative",
    ),
    "panic_mode": _trait(
        "Panic Mode",
        "Team trailing? Expect rushed mistakes.",
        category="negative",
        type="situational",
        condition="team_trailing",
        requirements=[],
        modifiers={"discipline": -6, "control": -5},
        synergy_tags={"resilience": -3},
        alignment="negative",
    ),
    "lazy": _trait(
        "Lazy",
        "Low hustle undermines development.",
        category="negative",
        type="passive_debuff",
        requirements=[],
        modifiers={"stamina": -5, "speed": -4},
        synergy_tags={"durability": -2},
        alignment="negative",
    ),
    "slow_starter": _trait(
        "Slow Starter",
        "Needs a month to find rhythm.",
        category="negative",
        type="situational",
        condition="season_opener_lag",
        requirements=[],
        modifiers={"contact": -5, "control": -5},
        synergy_tags={"momentum": -2},
        alignment="negative",
    ),
    "tight_shoulders": _trait(
        "Tight Shoulders",
        "Big games tighten mechanics and velo.",
        category="negative",
        type="situational",
        condition="big_game_stage",
        requirements=[],
        modifiers={"velocity": -4, "throwing": -4},
        synergy_tags={"composure": -3},
        alignment="negative",
    ),
    "cold_bat": _trait(
        "Cold Bat",
        "Extended droughts sap confidence.",
        category="negative",
        type="situational",
        condition="slump_active",
        requirements=[],
        modifiers={"contact": -6, "power": -4},
        synergy_tags={"momentum": -3},
        alignment="negative",
    ),
    "in_the_doldrums": _trait(
        "In the Doldrums",
        "Even heaters randomly stall.",
        category="negative",
        type="passive_debuff",
        requirements=[],
        modifiers={"contact": -3, "mental": -4},
        synergy_tags={"volatility": 2},
        alignment="negative",
    ),
    "killer_mentality": _trait(
        "Killer Mentality",
        "Overly aggressive decisions hurt the team.",
        category="negative",
        type="behavior",
        requirements=[],
        ai_tendency={"swing_aggression": 1.5},
        modifiers={"discipline": -6},
        synergy_tags={"aggression": 4},
        alignment="negative",
    ),
    "cannonball_arm": _trait(
        "Cannonball Arm",
        "Throws lasers but with no touch, creating errors.",
        category="negative",
        type="passive_debuff",
        requirements=[],
        modifiers={"throwing": 5, "fielding": -7},
        synergy_tags={"arm_strength": 2, "defense": -3},
        alignment="negative",
    ),
}


ROLE_TRAITS: Dict[str, Dict[str, object]] = {
    "cleanup_clutch_closer": _trait(
        "Clutch Closer",
        "Cleanup bat that relishes ninth-inning drama.",
        category="role",
        type="situational",
        condition="cleanup_spot",
        requirements=[{"stat": "power", "min": 60}, {"stat": "clutch", "min": 65}],
        modifiers={"power": 6, "clutch": 4},
        synergy_tags={"clutch": 3},
        alignment="role",
    ),
    "cleanup_power_surge": _trait(
        "Power Surge",
        "Cleanup swing scales with ducks on the pond.",
        category="role",
        type="situational",
        condition="cleanup_risp",
        requirements=[{"stat": "power", "min": 65}],
        modifiers={"power": 8},
        synergy_tags={"power": 3},
        alignment="role",
    ),
    "big_bopper": _trait(
        "Big Bopper",
        "Threatens multi-run blasts every trip.",
        category="role",
        type="passive_buff",
        requirements=[{"stat": "power", "min": 70}],
        modifiers={"power": 10},
        synergy_tags={"power": 4},
        alignment="role",
    ),
    "boomer": _trait(
        "Boomer",
        "Lives for big stages, drifts when stage is small.",
        category="role",
        type="situational",
        condition="big_game_stage",
        requirements=[{"stat": "clutch", "min": 60}],
        modifiers={"power": 5, "contact": 3},
        synergy_tags={"clutch": 2},
        alignment="role",
    ),
    "ace_strikeout_machine": _trait(
        "Strikeout Machine",
        "Ace who shoves until balls in play appear.",
        category="role",
        type="situational",
        condition="ace_start",
        requirements=[{"stat": "velocity", "min": 130}],
        modifiers={"velocity": 5, "movement": 4},
        synergy_tags={"power": 3},
        alignment="role",
    ),
    "ice_water": _trait(
        "Ice Water",
        "Ace calms runners on base instantly.",
        category="role",
        type="situational",
        condition="runners_in_scoring_pos",
        requirements=[{"stat": "clutch", "min": 68}],
        modifiers={"control": 4, "mental": 5},
        synergy_tags={"composure": 3},
        alignment="role",
    ),
    "complete_game_king": _trait(
        "Complete Game King",
        "Prefers to finish what he starts.",
        category="role",
        type="passive_buff",
        requirements=[{"stat": "stamina", "min": 65}],
        modifiers={"stamina": 6},
        synergy_tags={"durability": 3},
        alignment="role",
    ),
    "bullpen_nightmare": _trait(
        "Bullpen Nightmare",
        "Loves extending; early hooks hurt morale.",
        category="role",
        type="passive_debuff",
        requirements=[],
        modifiers={"mental": -4},
        synergy_tags={"resilience": -2},
        alignment="role",
    ),
    "table_setter": _trait(
        "Table Setter",
        "Leadoff wizard at finding base paths.",
        category="role",
        type="situational",
        condition="lineup_leadoff",
        requirements=[{"stat": "speed", "min": 58}, {"stat": "contact", "min": 50}],
        modifiers={"speed": 6, "contact": 5},
        synergy_tags={"speed": 2, "support": 2},
        alignment="role",
    ),
    "aggressive_slugger": _trait(
        "Aggressive Slugger",
        "Leadoff masher swinging early counts.",
        category="role",
        type="behavior",
        condition="lineup_leadoff",
        requirements=[{"stat": "power", "min": 60}],
        modifiers={"power": 5},
        ai_tendency={"swing_aggression": 1.25},
        synergy_tags={"power": 2},
        alignment="role",
    ),
    "pressure_cooker": _trait(
        "Pressure Cooker",
        "Closer whose heartbeat slows in the 9th.",
        category="role",
        type="situational",
        condition="closer_ninth",
        requirements=[{"stat": "clutch", "min": 70}],
        modifiers={"control": 5, "mental": 5},
        synergy_tags={"clutch": 3},
        alignment="role",
    ),
    "quick_strike": _trait(
        "Quick Strike",
        "Closer attacks hitters immediately.",
        category="role",
        type="behavior",
        condition="closer_role",
        requirements=[],
        ai_tendency={"attack_zone": 1.3},
        synergy_tags={"aggression": 2},
        alignment="role",
    ),
    "nerves_of_steel": _trait(
        "Nerves of Steel",
        "Final-out assassin.",
        category="role",
        type="situational",
        condition="closer_ninth",
        requirements=[{"stat": "mental", "min": 68}],
        modifiers={"mental": 6},
        synergy_tags={"composure": 3},
        alignment="role",
    ),
    "swiss_army_knife": _trait(
        "Swiss Army Knife",
        "Covers multiple spots without friction.",
        category="role",
        type="passive_buff",
        requirements=[{"stat": "fielding", "min": 55}],
        modifiers={"fielding": 3},
        synergy_tags={"utility": 3},
        alignment="role",
    ),
    "jack_of_all_trades": _trait(
        "Jack-of-all-Trades",
        "Does everything decently, nothing elite.",
        category="role",
        type="passive_buff",
        requirements=[],
        modifiers={"fielding": 2, "contact": 2, "power": -2},
        synergy_tags={"utility": 2},
        alignment="role",
    ),
    "flex_player": _trait(
        "Flex Player",
        "Great spot starter lacking everyday stamina.",
        category="role",
        type="situational",
        condition="spot_start",
        requirements=[],
        modifiers={"contact": 4, "stamina": -3},
        synergy_tags={"utility": 2},
        alignment="role",
    ),
    "pure_power_dh": _trait(
        "Pure Power",
        "DH built solely for taters.",
        category="role",
        type="passive_buff",
        condition="dh_assignment",
        requirements=[{"stat": "power", "min": 65}],
        modifiers={"power": 7},
        synergy_tags={"power": 3},
        alignment="role",
    ),
    "hit_and_sit": _trait(
        "Hit and Sit",
        "Elite bat, glove for emergencies only.",
        category="role",
        type="passive_buff",
        condition="dh_assignment",
        requirements=[{"stat": "contact", "min": 55}],
        modifiers={"contact": 6, "fielding": -4},
        synergy_tags={"power": 1, "defense": -2},
        alignment="role",
    ),
    "sluggers_delight": _trait(
        "Slugger's Delight",
        "Locked-in DH when focusing solely on offense.",
        category="role",
        type="situational",
        condition="dh_assignment",
        requirements=[{"stat": "power", "min": 60}],
        modifiers={"power": 6, "discipline": 3},
        synergy_tags={"power": 2},
        alignment="role",
    ),
    "backstop_king": _trait(
        "Backstop King",
        "Walls every pitch, frames everything.",
        category="role",
        type="passive_buff",
        condition="catcher_assignment",
        requirements=[{"stat": "fielding", "min": 60}, {"stat": "catcher_leadership", "min": 55}],
        modifiers={"fielding": 8},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "pitchers_best_friend": _trait(
        "Pitcher's Best Friend",
        "Keeps staff calm, guides sequencing.",
        category="role",
        type="aura",
        condition="catcher_assignment",
        requirements=[{"stat": "catcher_leadership", "min": 60}],
        team_effects={"pitcher_confidence": 4},
        synergy_tags={"leadership": 3},
        alignment="role",
    ),
    "arm_of_steel": _trait(
        "Arm of Steel",
        "Catcher guns down everything.",
        category="role",
        type="passive_buff",
        condition="catcher_assignment",
        requirements=[{"stat": "throwing", "min": 65}],
        modifiers={"throwing": 9},
        synergy_tags={"arm_strength": 3},
        alignment="role",
    ),
    "glove_monster": _trait(
        "Glove Monster",
        "First baseman saves infielders daily.",
        category="role",
        type="passive_buff",
        condition="first_base_assignment",
        requirements=[{"stat": "fielding", "min": 58}],
        modifiers={"fielding": 7},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "big_target": _trait(
        "Big Target",
        "Huge reach, limited mobility.",
        category="role",
        type="passive_buff",
        condition="first_base_assignment",
        requirements=[],
        modifiers={"fielding": 4, "speed": -4},
        synergy_tags={"defense": 2},
        alignment="role",
    ),
    "batting_behemoth": _trait(
        "Batting Behemoth",
        "1B slugger whose bat dwarfs glove.",
        category="role",
        type="passive_buff",
        condition="first_base_assignment",
        requirements=[{"stat": "power", "min": 65}],
        modifiers={"power": 8, "fielding": -3},
        synergy_tags={"power": 3},
        alignment="role",
    ),
    "quick_feet": _trait(
        "Quick Feet",
        "Second baseman erases milliseconds on pivots.",
        category="role",
        type="passive_buff",
        condition="second_base_assignment",
        requirements=[{"stat": "speed", "min": 55}],
        modifiers={"speed": 4, "fielding": 4},
        synergy_tags={"range": 2},
        alignment="role",
    ),
    "pivot_pro": _trait(
        "Pivot Pro",
        "Turns the 4-6-3 like clockwork.",
        category="role",
        type="situational",
        condition="double_play_situation",
        requirements=[{"stat": "fielding", "min": 55}],
        modifiers={"fielding": 6},
        synergy_tags={"range": 1},
        alignment="role",
    ),
    "range_god": _trait(
        "Range God",
        "Second baseman who lives in shallow right.",
        category="role",
        type="passive_buff",
        condition="second_base_assignment",
        requirements=[{"stat": "speed", "min": 60}],
        modifiers={"speed": 5, "fielding": 5},
        synergy_tags={"range": 3},
        alignment="role",
    ),
    "dynamic_defender": _trait(
        "Dynamic Defender",
        "Shortstop shuts down the middle.",
        category="role",
        type="passive_buff",
        condition="shortstop_assignment",
        requirements=[{"stat": "fielding", "min": 60}],
        modifiers={"fielding": 7},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "flashy": _trait(
        "Flashy",
        "SportsCenter shortstop, occasional bobbles.",
        category="role",
        type="passive_buff",
        condition="shortstop_assignment",
        requirements=[{"stat": "fielding", "min": 55}],
        modifiers={"fielding": 5, "throwing": 3, "discipline": -2},
        synergy_tags={"defense": 2},
        alignment="role",
    ),
    "anchor": _trait(
        "Anchor",
        "Dependable SS who just gets outs.",
        category="role",
        type="passive_buff",
        condition="shortstop_assignment",
        requirements=[{"stat": "fielding", "min": 58}],
        modifiers={"fielding": 6},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "rocket_arm": _trait(
        "Rocket Arm",
        "3B hose erases bunts and slow rollers.",
        category="role",
        type="passive_buff",
        condition="third_base_assignment",
        requirements=[{"stat": "throwing", "min": 70}],
        modifiers={"throwing": 9},
        synergy_tags={"arm_strength": 3},
        alignment="role",
    ),
    "hot_corner_hero": _trait(
        "Hot Corner Hero",
        "Makes every reaction play look simple.",
        category="role",
        type="passive_buff",
        condition="third_base_assignment",
        requirements=[{"stat": "fielding", "min": 60}],
        modifiers={"fielding": 7},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "speed_bump": _trait(
        "Speed Bump",
        "Slow reactions at third create miscues.",
        category="role",
        type="passive_debuff",
        condition="third_base_assignment",
        requirements=[],
        modifiers={"fielding": -6},
        synergy_tags={"defense": -3},
        alignment="negative",
    ),
    "fly_ball_master": _trait(
        "Fly Ball Master",
        "Tracks every deep shot calmly.",
        category="role",
        type="passive_buff",
        condition="outfield_assignment",
        requirements=[{"stat": "fielding", "min": 58}],
        modifiers={"fielding": 6},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "cannon_arm": _trait(
        "Cannon Arm",
        "Outfield missiles cut down greedy runners.",
        category="role",
        type="passive_buff",
        condition="outfield_assignment",
        requirements=[{"stat": "throwing", "min": 68}],
        modifiers={"throwing": 8},
        synergy_tags={"arm_strength": 3},
        alignment="role",
    ),
    "speedy_tracker": _trait(
        "Speedy Tracker",
        "CF-type range no matter where he plays.",
        category="role",
        type="passive_buff",
        condition="outfield_assignment",
        requirements=[{"stat": "speed", "min": 60}],
        modifiers={"speed": 5, "fielding": 4},
        synergy_tags={"range": 3},
        alignment="role",
    ),
    "outfield_glove_wizard": _trait(
        "Glove Wizard",
        "Rarely misplays a fly ball.",
        category="role",
        type="passive_buff",
        condition="outfield_assignment",
        requirements=[{"stat": "fielding", "min": 60}],
        modifiers={"fielding": 7},
        synergy_tags={"defense": 3},
        alignment="role",
    ),
    "icy_hot": _trait(
        "Icy Hot",
        "Starts slow each game but erupts after finding rhythm.",
        category="role",
        type="situational",
        condition="game_heat_up",
        requirements=[],
        modifiers={"contact": 4, "power": 4},
        synergy_tags={"momentum": 2},
        alignment="neutral",
    ),
    "baseball_iq": _trait(
        "Baseball IQ",
        "Always in the right spot, right decision.",
        category="role",
        type="passive_buff",
        requirements=[{"stat": "discipline", "min": 60}],
        modifiers={"discipline": 4, "mental": 4},
        synergy_tags={"awareness": 4},
        alignment="positive",
    ),
}


_SKILL_BUCKETS = (
    BATTER_TRAITS,
    FIELDING_TRAITS,
    PITCHING_TRAITS,
    MENTAL_TRAITS,
    SPECIALIZED_TRAITS,
    BAD_TRAITS,
    ROLE_TRAITS,
)

SKILL_DEFINITIONS: Dict[str, Dict[str, object]] = {}
for bucket in _SKILL_BUCKETS:
    for key, data in bucket.items():
        canonical = key.lower()
        entry = dict(data)
        entry.setdefault("category", "general")
        entry.setdefault("alignment", "positive")
        entry.setdefault("requirements", [])
        entry.setdefault("synergy_tags", {})
        entry.setdefault("type", "passive_buff")
        entry["key"] = canonical
        SKILL_DEFINITIONS[canonical] = entry

TRAIT_ALIASES = {
    "contact_artist": "contact_specialist",
    "strikeout_artist": "strikeout_king",
}
for alias, canonical in TRAIT_ALIASES.items():
    root = SKILL_DEFINITIONS.get(canonical)
    if root:
        SKILL_DEFINITIONS[alias] = root


__all__ = ["SKILL_DEFINITIONS", "TRAIT_ALIASES"]
