# pitch_definitions.py
# Defines the physics and attributes for all pitch types in the game.

ARM_SLOT_MODIFIERS = {
    # Vertical (Y) / Horizontal (X) multipliers, fatigue, and risk notes
    "Overhand": {
        "vertical_mult": 1.35,
        "horizontal_mult": 0.7,
        "control_penalty_mult": 0.95,
        "stamina_cost_mult": 1.08,
        "risk_type": "Shoulder",
        "group": "High",
        "plane_bonus": {"ride": 1.15, "drop": 1.08, "sweep": 0.88, "sink": 0.9, "fade": 0.95, "gyro": 1.05},
    },
    "High Three-Quarters": {
        "vertical_mult": 1.2,
        "horizontal_mult": 0.85,
        "control_penalty_mult": 0.98,
        "stamina_cost_mult": 1.04,
        "risk_type": "Shoulder",
        "group": "High",
        "plane_bonus": {"ride": 1.1, "drop": 1.05, "sweep": 0.93, "sink": 0.95, "fade": 0.98, "gyro": 1.02},
    },
    "Three-Quarters": {
        "vertical_mult": 1.0,
        "horizontal_mult": 1.0,
        "control_penalty_mult": 1.0,
        "stamina_cost_mult": 1.0,
        "risk_type": "Balanced",
        "group": "Neutral",
        "plane_bonus": {"ride": 1.0, "drop": 1.0, "sweep": 1.0, "sink": 1.0, "fade": 1.0, "gyro": 1.0},
    },
    "Low Three-Quarters": {
        "vertical_mult": 0.88,
        "horizontal_mult": 1.2,
        "control_penalty_mult": 1.05,
        "stamina_cost_mult": 0.98,
        "risk_type": "Elbow",
        "group": "Whip",
        "plane_bonus": {"ride": 0.95, "drop": 0.98, "sweep": 1.05, "sink": 1.08, "fade": 1.05, "gyro": 0.98},
    },
    "Sidearm": {
        "vertical_mult": 0.5,
        "horizontal_mult": 1.4,
        "control_penalty_mult": 1.12,
        "stamina_cost_mult": 0.95,
        "risk_type": "Elbow",
        "group": "Side",
        "plane_bonus": {"ride": 0.85, "drop": 0.9, "sweep": 1.1, "sink": 1.15, "fade": 1.05, "gyro": 0.95},
    },
    "Low Sidearm": {
        "vertical_mult": 0.4,
        "horizontal_mult": 1.6,
        "control_penalty_mult": 1.2,
        "stamina_cost_mult": 0.92,
        "risk_type": "Elbow",
        "group": "Side",
        "plane_bonus": {"ride": 0.8, "drop": 0.85, "sweep": 1.2, "sink": 1.2, "fade": 1.08, "gyro": 0.92},
    },
    "Submarine": {
        "vertical_mult": 0.25,
        "horizontal_mult": 1.85,
        "control_penalty_mult": 1.35,
        "stamina_cost_mult": 0.9,
        "risk_type": "Back",
        "group": "Sub",
        "plane_bonus": {"ride": 0.75, "drop": 0.8, "sweep": 1.25, "sink": 1.3, "fade": 1.1, "gyro": 0.9},
    },
}
PITCH_TYPES = {
    # --- FASTBALLS ---
    "4-Seam Fastball": {
        "velocity_mod": 1.02,
        "break_mod": 0.1,
        "stamina_cost": 1.0,
        "type": "Vertical",
        "family": "Fastball",
        "plane": "ride",
        "slot_groups": {"High": 1.05, "Neutral": 1.0},
        "desc": "Pure riding velocity up in the zone.",
    },
    "Rising Fastball": {
        "velocity_mod": 1.04,
        "break_mod": 0.05,
        "stamina_cost": 1.05,
        "type": "Vertical",
        "family": "Fastball",
        "plane": "ride",
        "slot_groups": {"High": 1.08, "Whip": 0.95},
        "desc": "Carry fastball built to tunnel with breakers.",
    },
    "2-Seam Fastball": {
        "velocity_mod": 0.97,
        "break_mod": 0.45,
        "stamina_cost": 1.0,
        "type": "Horizontal",
        "family": "Fastball",
        "plane": "sink",
        "slot_groups": {"Neutral": 1.0, "Whip": 1.05, "Side": 1.08},
        "desc": "Arm-side run with modest sink.",
    },
    "Turbo Sinker": {
        "velocity_mod": 1.0,
        "break_mod": 0.55,
        "stamina_cost": 1.12,
        "type": "Drop_Sink",
        "family": "Fastball",
        "plane": "sink",
        "slot_groups": {"Whip": 1.08, "Side": 1.1},
        "desc": "Velocity-driven sinker that bores late.",
    },
    "Shuuto": {
        "velocity_mod": 0.95,
        "break_mod": 0.65,
        "stamina_cost": 1.08,
        "type": "Horizontal",
        "family": "Fastball",
        "plane": "sink",
        "slot_groups": {"Side": 1.05, "Neutral": 1.0},
        "desc": "Violent inside ride to same-handed hitters.",
    },
    "Cutter": {
        "velocity_mod": 0.96,
        "break_mod": 0.5,
        "stamina_cost": 1.05,
        "type": "Horizontal",
        "family": "Fastball",
        "plane": "sweep",
        "slot_groups": {"High": 1.0, "Neutral": 1.02},
        "desc": "Short glove-side cut to jam barrels.",
    },
    "Power Cutter": {
        "velocity_mod": 0.99,
        "break_mod": 0.45,
        "stamina_cost": 1.12,
        "type": "Horizontal",
        "family": "Fastball",
        "plane": "sweep",
        "slot_groups": {"High": 1.02, "Neutral": 1.02},
        "desc": "Upper-90s gyro cutter.",
    },

    # --- BREAKING BALLS ---
    "Slider": {
        "velocity_mod": 0.88,
        "break_mod": 0.85,
        "stamina_cost": 1.2,
        "type": "Horizontal",
        "family": "Breaker",
        "plane": "sweep",
        "slot_groups": {"Neutral": 1.03, "Whip": 1.05, "Side": 1.08},
        "desc": "Tight glove-side tilt.",
    },
    "Sweeper": {
        "velocity_mod": 0.84,
        "break_mod": 1.05,
        "stamina_cost": 1.25,
        "type": "Horizontal",
        "family": "Breaker",
        "plane": "sweep",
        "slot_groups": {"Whip": 1.08, "Side": 1.12, "Sub": 1.12},
        "desc": "Whip slider with huge sweep.",
    },
    "Gyro Slider": {
        "velocity_mod": 0.9,
        "break_mod": 0.7,
        "stamina_cost": 1.18,
        "type": "Horizontal",
        "family": "Breaker",
        "plane": "gyro",
        "slot_groups": {"High": 1.02, "Neutral": 1.02},
        "desc": "Bullet slider tunneling off four-seamers.",
    },
    "Curveball": {
        "velocity_mod": 0.78,
        "break_mod": 1.1,
        "stamina_cost": 1.12,
        "type": "Vertical",
        "family": "Breaker",
        "plane": "drop",
        "slot_groups": {"High": 1.08, "Neutral": 1.02},
        "desc": "Classic 12-6 hammer.",
    },
    "Power Curve": {
        "velocity_mod": 0.83,
        "break_mod": 0.95,
        "stamina_cost": 1.18,
        "type": "Vertical",
        "family": "Breaker",
        "plane": "drop",
        "slot_groups": {"High": 1.05, "Neutral": 1.05},
        "desc": "Firm breaker with depth.",
    },
    "Knuckle Curve": {
        "velocity_mod": 0.8,
        "break_mod": 1.2,
        "stamina_cost": 1.22,
        "type": "Vertical",
        "family": "Breaker",
        "plane": "drop",
        "slot_groups": {"High": 1.1, "Neutral": 1.05},
        "desc": "Spike curve with severe depth.",
    },
    "Slow Curve": {
        "velocity_mod": 0.66,
        "break_mod": 1.25,
        "stamina_cost": 0.95,
        "type": "Vertical",
        "family": "Breaker",
        "plane": "drop",
        "slot_groups": {"High": 1.04, "Neutral": 1.02},
        "desc": "Show-me rainbow for timing disruption.",
    },
    "Slurve": {
        "velocity_mod": 0.82,
        "break_mod": 0.95,
        "stamina_cost": 1.18,
        "type": "Diagonal",
        "family": "Breaker",
        "plane": "sweep",
        "slot_groups": {"Whip": 1.06, "Side": 1.04},
        "desc": "Hybrid slider/curve with depth.",
    },

    # --- DROP / SINK / SPLIT ---
    "Forkball": {
        "velocity_mod": 0.84,
        "break_mod": 0.95,
        "stamina_cost": 1.35,
        "type": "Vertical",
        "family": "Splitter",
        "plane": "sink",
        "slot_groups": {"High": 1.0, "Neutral": 1.02},
        "desc": "Heavy plunge with limited feel.",
    },
    "Splitter": {
        "velocity_mod": 0.9,
        "break_mod": 0.8,
        "stamina_cost": 1.2,
        "type": "Vertical",
        "family": "Splitter",
        "plane": "sink",
        "slot_groups": {"Neutral": 1.05, "Whip": 1.05},
        "desc": "Late dive off fastball look.",
    },
    "Split-Change": {
        "velocity_mod": 0.86,
        "break_mod": 0.9,
        "stamina_cost": 1.15,
        "type": "Vertical",
        "family": "Splitter",
        "plane": "fade",
        "slot_groups": {"Whip": 1.05, "Side": 1.08},
        "desc": "Pronounced fade with tumble.",
    },
    "Sinker": {
        "velocity_mod": 0.93,
        "break_mod": 0.65,
        "stamina_cost": 1.05,
        "type": "Drop_Sink",
        "family": "Fastball",
        "plane": "sink",
        "slot_groups": {"Neutral": 1.02, "Whip": 1.05, "Side": 1.05, "Sub": 1.05},
        "desc": "Heavy bore with gloveside finish.",
    },

    # --- OFFSPEED / CHANGE OF PACE ---
    "Changeup": {
        "velocity_mod": 0.82,
        "break_mod": 0.45,
        "stamina_cost": 0.92,
        "type": "Offspeed",
        "family": "Changeup",
        "plane": "fade",
        "slot_groups": {"Neutral": 1.02, "Whip": 1.04},
        "desc": "Straight change with modest fade.",
    },
    "Circle Change": {
        "velocity_mod": 0.8,
        "break_mod": 0.55,
        "stamina_cost": 0.92,
        "type": "Offspeed",
        "family": "Changeup",
        "plane": "fade",
        "slot_groups": {"Whip": 1.05, "Side": 1.05},
        "desc": "Arm-side fade with tumble.",
    },
    "Vulcan Change": {
        "velocity_mod": 0.78,
        "break_mod": 0.65,
        "stamina_cost": 1.0,
        "type": "Offspeed",
        "family": "Changeup",
        "plane": "fade",
        "slot_groups": {"Neutral": 1.02, "Side": 1.07, "Sub": 1.08},
        "desc": "Splitter-style change with late dive.",
    },
    "Knuckleball": {
        "velocity_mod": 0.62,
        "break_mod": 1.5,
        "stamina_cost": 0.55,
        "type": "Erratic",
        "family": "Special",
        "plane": "sweep",
        "slot_groups": {"Any": 1.0},
        "desc": "Unpredictable float with chaos.",
    },
}